### ISSUE TITLE
aoc 2022 day 7 - Rc<Dir> vs Rc<RefCell<Dir>>

### ISSUE THREAD

**Issue by tivrfoa** [UncleScientist/aoclib-rs#1]
Not an issue, just a question/comment =)

https://github.com/UncleScientist/aoclib-rs/blob/main/src/bin/run-aoc/aoc2022/aoc2022_07.rs#L9

It's interesting that you used `Rc<Dir>`, instead of `Rc<RefCell<Dir>>`.

Using `Rc<Dir>` you then need interior mutability for each field, in this case: size and subdir. Right?

I did it like this:
https://github.com/tivrfoa/advent-of-code-2022/blob/main/src/day7.rs#L14

But in my first attempt I avoided using Rc and RefCell:
https://github.com/tivrfoa/advent-of-code-2022/blob/main/src/day7-part2.rs#L8

**Comment by UncleScientist** [comment]
Ah, yeah, that's a good approach - I did it the way I did it so that I could avoid lifetimes :)
